### ISSUE TITLE
access "studies" endpoint fails, but used to work. 

### ISSUE THREAD

**Issue by circles417** [simon-lenau/prolific.api#1]
Problem:  access "studies" endpoint fails, but used to work.  Error messages for as_list TRUE and FALSE are shown.  

prolific_api_access <-  api_access(api_token = Sys.getenv('token'))

access(
      prolific_api_access,
      endpoint = "studies",
      method = "get",
      as_list = TRUE
    ) 

Warning: Some columns are a multi-column type (such as a matrix column): [7]. setDT will retain these columns as-is but subsequent operations like grouping and joining may fail. Please consider as.data.table() instead which will create a new column for each embedded column.Error in data.table::setDT(output) : 
  All elements in argument 'x' to 'setDT' must be of same length, but the profile of input lengths (length:frequency) is: [2:1, 76:14]
The first entry with fewer than 76 entries is 7

access(
  prolific_api_access,
  endpoint = "studies",
  method = "get",
  as_list = FALSE
)

Error in output$results : $ operator is invalid for atomic vectors

**Comment by circles417** [comment]
Rerunning it I get a new error message (Error in data.table(x) : could not find function "data.table") so I `library(data.table)` and the code works again.  I'm not sure if it was a local package issue or perhaps something with Prolific's API.

**Comment by circles417** [comment]
Resolved by reinstalling with:
devtools::install_github('simon-lenau/prolific.api')

instead of:
install.packages('prolific.api')

**Comment by simon-lenau** [comment]
Thanks for the hint! The problem was caused by changes in the API's data structure. The update (which is now also available from CRAN) should solve the problem.
