### ISSUE TITLE
Suggestion: Vignette description for exporting demographic data

### ISSUE THREAD

**Issue by jmgirard** [simon-lenau/prolific.api#3]
One of my main use cases for the package was to be able to download the participants' demographic data into R. It would be great to add an example of how to do this to a vignette. I figured it out from the API documentation. This is the approach I used:

```r
api <- api_access(api_token = "<your_api_token>")
demo <- api$access(
  endpoint = c("studies", "<your_study_id>", "export"),
  method = "get"
)
demo_df <- read.csv(text = demo)
```

**Comment by simon-lenau** [comment]
Indeed, that's a useful new feature that was not available a few months ago.
I was not aware that this is possible now, so thanks for the hint!
I'm going to include it in the next update of the vignettes.
